# This is a basic workflow to help you get started with Actions

name: UnitTest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Workaround composer failed opening composer.lock
        run: |
          sudo chown -R runner .

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: intl
          tools: composer:v2 behat
          coverage: xdebug
          ini-values: session.use_strict_mode=1, session.use_trans_id=1

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: PhpStan
        run: vendor/bin/phpstan

      - name: PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix

      - name: CodeClimate (1/2) - Before
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: PHPUnit (php-actions)
        run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

      - name: Coverage - merge data
        run: vendor/bin/phpcov  merge coverage/ --clover build/logs/clover.xml

      - name: CodeClimate (2/2) - Report
        run: |
          mv build/logs/clover.xml coverage/
          ls -l coverage/
          vendor/bin/phpcov  merge coverage/ --clover build/logs/clover.xml
          ./cc-test-reporter after-build --coverage-input-type clover ${{secrets.CC_TEST_REPORTER_ID}}