# This is a basic workflow to help you get started with Actions

name: UnitTest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.4']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Workaround composer failed opening composer.lock
        run: |
          sudo chown -R runner .

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: intl
          tools: composer:v2 behat
          coverage: xdebug
          ini-values: session.use_strict_mode=1, session.use_trans_id=1

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: PhpStan
        run: vendor/bin/phpstan

      - name: PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix

      - name: PHPUnit (php-actions)
        run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

      - name: Coverage - merge data
        run: vendor/bin/phpcov  merge coverage/ --clover build/logs/clover.xml

      - uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: 126eb45d7e76c2b3564b382ca3b4481bb7745d20283655f38e5fafefddef6540
        with:
          coverageLocations: |
            ${{github.workspace}}/build/logs/clover.xml:clover